### ISSUE TITLE
split issue 

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTsPyMM#17]
Hey @stnava , 

Okay, so I'm getting the same split error even after updating (see below).   This file is the one with 10 components "/Users/ntustison/Data/Stone/LIMBIC/NRG/ANTsLIMBIC/sub08C105120Yr/ses-1/rsfMRI-LR/000/ANTsLIMBIC_sub08C105120Yr_ses-1_rsfMRI-LR_000.nii.gz".  I assumed that the script would skip these files but perhaps I'm misunderstanding what is supposed to happen.  

Also, as I'm looking at the screen dump, I'm seeing another potential issue.  Basically, in my conversion from BIDS to NRG, I had originally changed from "dwi_ap" and "dwi_pa" to "rsfMRI_LR" and "rsfMRI_RL" but that caused issues with the valid filename checker because "_" is used as a separate.  However, when I switched to using "rsfMRI-LR" and "rsfMRI-RL", a file path seems to get mangled (see line 5 below).

```
overmodX is : rsfMRI
example image name is : 
['/Users/ntustison/Data/Stone/LIMBIC/NRG/ANTsLIMBIC/sub08C105120Yr/ses-1/rsfMRI-LR/000/ANTsLIMBIC_sub08C105120Yr_ses-1_rsfMRI-LR_000.nii.gz', '/Users/ntustison/Data/Stone/LIMBIC/NRG/ANTsLIMBIC/sub08C105120Yr/ses-1/rsfMRI-RL/000/ANTsLIMBIC_sub08C105120Yr_ses-1_rsfMRI-RL_000.nii.gz']
subjectpropath is
/Users/ntustison/Data/Stone/LIMBIC/Processed/ANTsLIMBIC/sub08C105120Yr/ses-1/rsfMRI/RL_000
Modality specific processing: rsfMRI execution 
/Users/ntustison/Data/Stone/LIMBIC/Processed/ANTsLIMBIC/sub08C105120Yr/ses-1/rsfMRI/RL_000/ANTsLIMBIC-sub08C105120Yr-ses-1-rsfMRI-RL_000_000
/Users/ntustison/Data/Stone/LIMBIC/Processed/ANTsLIMBIC/sub08C105120Yr/ses-1/rsfMRI/RL_000
/Users/ntustison/Data/Stone/LIMBIC/NRG/ANTsLIMBIC/sub08C105120Yr/ses-1/rsfMRI-LR/000/ANTsLIMBIC_sub08C105120Yr_ses-1_rsfMRI-LR_000.nii.gz
Using group template:
ANTsImage (LPI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (297, 366, 297)
	 Spacing    : (0.5, 0.5, 0.5)
	 Origin     : (75.1203, 75.4104, -77.5003)
	 Direction  : [-1. -0. -0.  0. -1. -0.  0. -0.  1.]

rsf length 2
initial average for rsf
An error occurred while processing rsfMRI: 'NoneType' object has no attribute 'split'
done with rsfMRI
```

**Comment by stnava** [comment]
technically - valid modality names are: 

```python
antspymm.get_valid_modalities(>>> antspymm.get_valid_modalities("long")
['T1w', 'NM2DMT', 'rsfMRI', 'rsfMRI_LR', 'rsfMRI_RL', 'DTI', 'DTI_LR', 'DTI_RL', 'T2Flair', 'dwi', 'func', 'perf']
```
and switching a dwi name to a rsfmri name .... probably not what you meant?

anyway - the file path does pass but it doesn't contain "valid modalities" ...  at least "technically speaking" .... I suppose that check should be added to `antspymm.validate_nrg_file_format` ....  it may happen that it works anyway though b/c I am not checking the _RL _LR very strictly.

so - in short - switch you  "-" to "_"  and you will probably be good with filenames.    

nevertheless - the error you are getting is from these lines and probably unrelated to filenames:

https://github.com/ANTsX/ANTsPyMM/blob/main/antspymm/mm.py#L6564-L6571

**Comment by stnava** [comment]
if just print some debugging stuff like:
print("loop1")
            rsfavg1, hlinds = loop_timeseries_censoring( rsf_image1, 0.1 )

print( rsfavg1 )
print( hlinds )
print('loop2')
            rsfavg1, hlinds = loop_timeseries_censoring( rsf_image1, 0.1 )

print( rsfavg2 )
print( hlinds )


that woul help

**Comment by ntustison** [comment]
Awesome.  Thanks.  I'll debug and let you know.  

Okay, yeah, so that's what I thought re. the filenames but I was a little bit confused in specifying "_" as a generic file separator in the path while simultaneously having an exception in the modality name.

**Comment by stnava** [comment]
also - print the images ... I wonder if one of them Is "None".    that 's usually what that generic python error means ....  you are passing None to an operator

**Comment by stnava** [comment]
one note:  I would expect to see a warning here:

initial average for rsf
__right here__
An error occurred while processing rsfMRI: 'NoneType' object has no attribute 'split'

if the issue were the small time dimension ... I added a user warn print out ...

**Comment by stnava** [comment]
this could also be the source of the error - an off by one issue:

https://github.com/ANTsX/ANTsPyMM/blob/71c88761c16081d2b02b372d4477e6be68538ebe/antspymm/mm.py#L2897-L2903

**Comment by stnava** [comment]
e.g. maybe should be 
```
max_t=x.shape[3]
```

**Comment by ntustison** [comment]
Thanks.  Trying that out now.

**Comment by ntustison** [comment]
Okay, it throws an error [here](https://github.com/ANTsX/ANTsPyMM/blob/main/antspymm/mm.py#L9900).

**Comment by stnava** [comment]
ok - some information is missing here.  

you previous said "it only has 10 time points". 

I added this:

https://github.com/ANTsX/ANTsPyMM/blob/71c88761c16081d2b02b372d4477e6be68538ebe/antspymm/mm.py#L9985-L9987

so it ( the "short" rsfMRI) should never enter the code you referred to ... at what point  does it get to this code?  what do the "print" outputs show?

**Comment by ntustison** [comment]
Ooops, sorry, no it's getting caught on the one with 600 time points.  I didn't know what the cause was before.  I'm actually looking at the sklearn code now to see what's wrogn with the input data.  I'll send it to you when I figure out more information.

**Comment by stnava** [comment]
ok - this is unusual ... in the 10s of 1000s of rsfmri that have gone through this step, I've not seen this come up .... can you share the image?

also - you should be able to reproduce this with just 2 lines:

```python
rsf_image1=read(fn)
rsfavg1, hlinds = loop_timeseries_censoring( rsf_image1, 0.1 )
```

since not much happens before this point other than reading the image

**Comment by ntustison** [comment]
Yeah, I would assume that it wasn't something you did but it's always fun to try to hunt it down to figure out what it is.  

I just stumbled across [this](https://github.com/scikit-learn/scikit-learn/issues/24238), did the proposed solution, and it looks to be working now.  I have to run and do an errand but I'll be sure to double check later tonight.

**Comment by stnava** [comment]
ok ... that (sort of) makes sense .... nevertheless this (inadvertently) uncovered several other edge cases that are probably better handled now.
