### ISSUE TITLE
separator

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTsPyMM#18]
Okay, revisiting the path.  In the case where I simultaneously have "DTI_LR" and "ses-1", would you change it to "ses1" and use "-" as a separator?

```
antspymm.validate_nrg_file_format("/Users/ntustison/Data/Stone/LIMBIC/NRG/ANTsLIMBIC//sub08C105120Yr/ses-1/DTI_LR/000/ANTsLIMBIC_sub08C105120Yr_ses-1_DTI_LR_000.json", "_")
['ANTsLIMBIC', 'sub08C105120Yr', 'ses-1', 'DTI', 'LR', '000']
(False, "Filename does not have exactly 5 parts separated by '_'. Found 6 parts.")
```

**Comment by stnava** [comment]
I suppose ... could also just try DTILR ... it would probably work. 

the original intent was to use "-" as separator .... before getting sucked into the bids world ...

**Comment by ntustison** [comment]
Perfect.  Thanks.
